---
- include_tasks:
    file: check_vars.yml
    apply:
      tags: ["ssmtp","mail","check"]
  tags:
    - always

- include_tasks:
    file: ssmtp.yml
    apply:
      tags: ["ssmtp","mail"]
  tags:
    - always
